version: "3.8"
services:
  notiplog-srv:
    container_name: notiplog-srv
    build:
      context: .
    environment:
      - PORT=8089
      - TZ=America/Toronto
    restart: unless-stopped
    volumes:
      - notiplog-db:/srv/database
    
  notiplog-ws:
    image: nginx
    container_name: notiplog-ws
    ports:
      - 8089:80
    volumes:
      - ./00-notiplog-site.conf:/etc/nginx/conf.d/default.conf

networks:
    default:
        external: false
        name: "notiplog-net"
        driver: bridge

volumes:
  notiplog-db:
    external: false
